### ISSUE TITLE
How to include JS?

### ISSUE THREAD

**Issue by sahilbabbar** [flipswitchingmonkey/BlazorFullCalendar#2]
How to include the JavaScript file, mentioned in README?
```
<script src="_content/BlazorFullCalendar/BlazorFullCalendar.js"></script>
```
Where is this file?

**Comment by flipswitchingmonkey** [comment]
That's embarrassing ;) There was a leftover .gitignore in the repo that didn't commit the wwwroot folder that contains the .js file ;)
So... it should be there now!
