### ISSUE TITLE
Can you please make this same project for Blazor WASM 

### ISSUE THREAD

**Issue by imprathamesh** [flipswitchingmonkey/BlazorFullCalendar#4]
I tried in blazor wasm but its not working the all main.css and main.min,js files cdn of full calendar showing 403 error.

**Comment by flipswitchingmonkey** [comment]
I'm currently not working with Blazor and don't have the time outside work to do this, so unfortunately I won't be able to do this anytime soon, sorry.

**Comment by imprathamesh** [comment]
Okay Sir.
