### ISSUE TITLE
There is no response on the click of ClickEvent.

### ISSUE THREAD

**Issue by ioer2008** [flipswitchingmonkey/BlazorFullCalendar#6]
![image](https://user-images.githubusercontent.com/12724988/113274885-c04d8e00-9310-11eb-8c21-99ac23ec3b52.png)
in this line

**Comment by AsafBen179** [comment]
hi , i am fix the problem by adding this line:
<script src='https://momentjs.com/downloads/moment-with-locales.js'></script>

into _Host.cshtml <head>
